# ------------------------
# Server
# ------------------------
server.port=8085
server.servlet.context-path=/api

# ------------------------
# MySQL Datasource
# ------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/db_eventos_peru?
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ------------------------
# Mail (SMTP Gmail)
# ------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=roman520fr@gmail.com
spring.mail.password=nmhy bzdg oweh igrt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ------------------------
# JWT
# ------------------------
app.jwt.issuer=eventos-auth
app.jwt.access-exp-min=60
app.jwt.secret=uW4d/tvW0KOJF1i9+4AYeTKERT9/hmXaXqOMqCr/tz0iCGjuMrQ2/kbbjhbuKXvj4u5P7OpZBzsZsuxoR+62Tg==

# ------------------------
# Verification config
# ------------------------
app.verification.ttl-minutes=10
app.verification.max-attempts=5
app.verification.resend-window-seconds=60

# ------------------------
# CORS (para tu frontend)
# ------------------------
app.cors.frontend-origin=http://localhost:3000
#app.cors.frontend-origin=${FRONT_ORIGIN}
# Página del front donde el usuario hará el reset
app.reset.frontend-url=HTTP://localhost300/reset-password


spring.flyway.enabled=false
